### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by NatoBoram** [NatoBoram/switcheroo#20]
Upgrading to 1.21 started, but I have a hard time figuring out how to calculate the damage done to specific entities considering enchantments.

It's possible that the next update simply won't have weapon selection.

**Comment by horseloyal** [comment]
Do you think there would be a possibility of you releasing the 1.21 version without weapon support, even just temporarily? After all the mod is much more useful beyond just weapons, and it would also give you less stress and more time to solve the weapon issue. Good mod though 👍

**Comment by NatoBoram** [comment]
Related issue:

* https://github.com/FabricMC/fabric/issues/337
